### ISSUE TITLE
Problem with a standalone executable

### ISSUE THREAD

**Issue by nathalierun** [jmoenig/Snap--Build-Your-Own-Blocks#1527]
Hello,

As I already said (see the issue #1520 (https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues/1520)), I have a recursive function to draw the Sierpinski triangle, and the standalone executable doesn't work (exported with this page http://snapp.citilab.eu/). 
Someone could explain it ? I wonder whether the problem comes from recursivity.

Thanks by advance.

**Comment by bromagosa** [comment]
Hi @nathalierun!

Snapp<i>!</i> is separate project that you can find at https://github.com/Rydion/Snapp/. It was Adrian's final project at university, and he very generously maintains it in his free time, so be patient if he takes a while to reply :)

In the meantime, can you share your project so I can check whether there are any blocks or features that have been added to Snap<i>!</i> since Snapp<i>!</i> got its last update and thus may not yet be supported?

**Comment by nathalierun** [comment]
Hi @bromagosa 

Here is my shared project.
http://snap.berkeley.edu/snapsource/snap.html#present:Username=nathalierun&ProjectName=Sierpinski.Aleatoire.p

Thank you to take my request into acount.

**Comment by bromagosa** [comment]
At first I thought it may be that the
![image](https://cloud.githubusercontent.com/assets/1016697/20960180/729cd08a-bc5f-11e6-853d-19ee765f2cd3.png) block was not supported by Snapp<i>!</i>, as it's relatively new in Snap<i>!</i>, but it [seems to be](https://github.com/Rydion/Snapp/blob/master/working/result/threads.js#L2748), so I'm a bit lost here. I can't see anything in your project that shouldn't be runnable by the Snapp<i>!</i> environment.

@Rydion, any insights into this?

**Comment by jguille2** [comment]
But maybe  your first thought is the key,@bromagosa.
Snapp! has this [block defined](https://github.com/Rydion/Snapp/blob/master/working/result/threads.js#L2748), but with a non-firstclass aproximation. This block accepts their six string options... but I think I can't put 
![att_ex](https://cloud.githubusercontent.com/assets/2926315/20960913/eb686f62-bc62-11e6-8059-d9073eede8ce.png)
like a current option.

**Comment by jmoenig** [comment]
My uneducated guess is that Snapp's equivalent of trying to "shrink the code image" is removing some stuff that's not obviously a dependency of something else, perhaps because it's not getting directly invoked but through a meta-level. It would be a worthwhile experiment to just leave out this "shrinking optimization", don't you think?

**Comment by bromagosa** [comment]
@jmoenig yep, that's what I advocated for in the first place, just keep the whole codebase and hide the stage buttons.

The shrinking is cool, and is actually what Adrian's project was mostly about (parsing, AST-walking and auto-modifying JS), but it doesn't significantly reduce size or load speeds, and it makes maintenance much harder.

**Comment by jmoenig** [comment]
Sure. We know from Smalltalk that shrinking doesn't work. Correction: Shrinking only works on code that doesn't go meta. As soon as you concatenate the string contents of a bunch of variables, combine it with the result of a dynamic function call, and then evaluate some other function that will in turn evaluate the stuff you've glued together before, you're basically off the grid. You *can* try to guess some level(s) of meta-ness, by perhaps scanning for ```#perform:``` and then looking up the argument, but what if the argument is a function call or the result of a Block (in Smalltalk)? I believe the official right way to "shrink" something today is to modularize it when you bootstrap it. Although that will run into the same problems eventually :-/

Can we still (convince Adrian to) maybe not shrink Snapp at all? This should be easy, right? Just omit the shrinking part, which is probably a single function call...

**Comment by bromagosa** [comment]
Totally agree. The right way to shrink in Smalltalk is what Pharo is doing, just keep enhancing VMs and images to be smaller and more performant altogether, then ship the whole thing, which now weighs about 30Mb, which is nothing nowadays!

I guess we can (convince @Rydion to) omit the shrinking part. The shrinking doesn't happen dynamically, so it should just be a matter of replacing the shrunk codebase by the original one plus a bunch of changes to run the particular project, go full screen, and hide the stage controls.

If @Rydion is too busy I could take a look too.

**Comment by Rydion** [comment]
Hi, I'm aware of the issues with trying to shrink the source code of Snap!.
I'm currently finishing a rewrite of Snapp! and one of the things that will
change is that it won't be using the shrinked code anymore. Just a slightly
modified version of Snap! that hides everything but the stage as @bromagosa
suggested.
I'll let you know once it's done.

**Comment by jmoenig** [comment]
@Rydion awesome, thanks!

**Comment by bromagosa** [comment]
@Rydion if I can help in any way please let me know :)

**Comment by Rydion** [comment]
Hi, happy new year everyone!

So, it took a while but I've finally finished the Snapp*!* rewrite. The new version is up and running and working nicely. There are still some things that I want to change/fix but nothing too major.

This new version uses the standard version of Snap*!* with only slight modifications as promised, there shouldn't be any more issues with projects not working from now on.

PS: I haven't been able to test the new version on Mac nor Linux and the only browsers I have available atm is Chrome and IE. It would be nice if some of you could test it and see if it still plays nicely with your setups.

**Comment by bromagosa** [comment]
These are fantastic news! Thank you @Rydion!

Confirmed to work in GNU/Linux 64b. The only thing that didn't work is the automatic OS detection in the drop down menu, but that's just a minor annoyance.

@jmoenig @brianharvey @cycomachead can somebody test the MacOSX one? :)

**Comment by jmoenig** [comment]
This is great, @Rydion !
I've just tried it on MacOS both 32 and 64 bit version, but when I try to run the app my Mac tells me "The application ... can't be opened".

**Comment by Rydion** [comment]
@jmoenig I guess you are using Safari? I'll look into it.

**Comment by jmoenig** [comment]
@Rydion thanks! I was using Chrome to access the Snapp site. Does it matter?

**Comment by Rydion** [comment]
Really? Well that is strange. On Windows chrome it works. Is the Mac
version that different?

**Comment by jmoenig** [comment]
Wait! It *does* create a zip file, which I extract to get the app. Then, when I double-click on the resulting app MacOS tells me that it can't be opened. If I remember right we had this issue at some time in the past and it was a really easy fix, just one flag in a file...

**Comment by Rydion** [comment]
Interesting... I was quite sure that I was setting everything correctly.
Maybe I missed something. I'll check once I get back home.

**Comment by bromagosa** [comment]
Hey! We've just discovered that `nwjs` is not executable in the OSX version. It should be a very simple fix, right?

**Comment by Rydion** [comment]
Yes it's the same problem @jmoenig pointed out. I probably messed up
setting the appropiate flags while zipping the file. I'll let you know as
soon as I've fixed it.

**Comment by cycomachead** [comment]
I couldn't get the site to work in Safari, but there might also be an issue with CodeSigning - otherwise you'll have to explicitly allow the app to run from System Prefs.

**Comment by Rydion** [comment]
Hi, the new version is up and running.

I've solved the issue with Mac OS (I hope) there was indeed a flag I had missed. If someone could test it for me it would be awesome.

I've also added the "detect OS" feature back in.

@cycomachead If you confirm that it's indeed a bug could you tell me exactly what the problem is? Does the app not work at all or aren't you able to generate the executable? If it's the latter I also fixed a bug that was keeping the app from working with IE11, maybe it's related. If it's the former I may have some ideas but I would need to test them with a Mac myself.

If you find anything else please let me know so that I can iron out all the remaining issues.

**Comment by brianharvey** [comment]
Doesn't work for me on MacOS 10.11.6.  It makes an app, and the app starts and immediately dies. (I can see the brief flash of the outline of a window appearing.)  Dunno if this helps but here's the console log:

<img width="559" alt="console001" src="https://cloud.githubusercontent.com/assets/3885074/21831834/a5f9e78a-d75b-11e6-947c-f8378e32c115.png">

**Comment by Rydion** [comment]
Interesting, the method used to create the executable hasn't really
changed. I'll see if I can pinpoint the problem.

**Comment by bromagosa** [comment]
@brianharvey have you tried with a different project?

**Comment by Rydion** [comment]
@bromagosa That may be worth a try, but I'm guessing that if the entire
thing crashes the problem is probably related to NW.js or how the
executable is being built.

**Comment by micahcowan** [comment]
When I tried to open it, I got a message that it couldn't open because the executable was missing.

But nwjs was in MacOS and had +x set for all. I wasn't sure this was necessary, but edited Info.plist to change CFBundleExecutable from njws to MacOS/njws. At that point I ran into @brianharvey's issue: opens, then closes immediately.

Strangely, if I change the Info.plist back to its original contents, or even blow the app away and re-unzip, I still get @brianharvey's issue, and not the "executable is missing" issue. I don't understand that.

**Comment by Rydion** [comment]
Hi, thank you for your help. I was able to take a quick look at the issue
myself and I had the problem described by @bryanharvey. It does seem to be
a problem with the app structure, but I have no idea why it's happening. I
have copied the entire app folder from the previous Snapp! version and as
far as I know that one was working correctly. Maybe at some point along the
way something got screwed up. I will compare both versions once again to
see if I can find the issue.

**Comment by bromagosa** [comment]
You could otherwise use an automatic packager like [nw-builder](https://github.com/nwjs/nw-builder). I'm using it for Snap4Arduino since last summer, and it really works like a charm :)

**Comment by brianharvey** [comment]
I tried running nwjs in a terminal and got this:

bhpro13.local% ./nwjs 
LaunchProcess: failed to execvp:
/Users/bh/Desktop/breakout.app/Contents/Frameworks/nwjs Helper.app/Contents/MacOS/nwjs Helper
LaunchProcess: failed to execvp:
/Users/bh/Desktop/breakout.app/Contents/Frameworks/nwjs Helper.app/Contents/MacOS/nwjs Helper
LaunchProcess: failed to execvp:
/Users/bh/Desktop/breakout.app/Contents/Frameworks/nwjs Helper.app/Contents/MacOS/nwjs Helper
[66110:0112/094328:WARNING:file_descriptor_set_posix.cc(30)] FileDescriptorSet destroyed with unconsumed descriptors: 0/1
[66110:0112/094329:WARNING:file_descriptor_set_posix.cc(30)] FileDescriptorSet destroyed with unconsumed descriptors: 0/1

-----------------------

Frameworks/nwjs Helper.app/Contents/Macos/ has no executable files.

If I mark nwjs Helper as executable, then run the app, it starts, puts up a big white window on the screen, and then dumps a huge stack trace on the terminal starting like this:

bhpro13.local% ./nwjs 
[66829:0112/095028:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'hasOwnProperty' of undefined
    at file:///var/folders/dh/qzbgtp5j4691byv02vkth71rr4fgb6/T/.org.chromium.Chromium.XEktIh/morphic.js:1527:20
    at Array.some (native)
    at enableRetinaSupport (file:///var/folders/dh/qzbgtp5j4691byv02vkth71rr4fgb6/T/.org.chromium.Chromium.XEktIh/morphic.js:1525:27)
    at file:///var/folders/dh/qzbgtp5j4691byv02vkth71rr4fgb6/T/.org.chromium.Chromium.XEktIh/morphic.js:1212:1
[66829:0112/095028:INFO:CONSOLE(1527)] "Uncaught TypeError: Cannot read property 'hasOwnProperty' of undefined", source: file:///var/folders/dh/qzbgtp5j4691byv02vkth71rr4fgb6/T/.org.chromium.Chromium.XEktIh/morphic.js (1527)
[66829:0112/095028:ERROR:nw_shell.cc(336)] TypeError: undefined is not a function
    at new TriggerMorph (file:///var/folders/dh/qzbgtp5j4691byv02vkth71rr4fgb6/T/.org.chromium.Chromium.XEktIh/morphic.js:9126:10)
    at file:///var/folders/dh/qzbgtp5j4691byv02vkth71rr4fgb6/T/.org.chromium.Chromium.XEktIh/widgets.js:94:29
[66829:0112/095028:INFO:CONSOLE(9126)] "Uncaught TypeError: undefined is not a function", source: file:///var/folders/dh/qzbgtp5j4691byv02vkth71rr4fgb6/T/.org.chromium.Chromium.XEktIh/morphic.js (9126)
[66829:0112/095028:ERROR:nw_shell.cc(336)] TypeError: undefined is not a function

When we get that kind of message in the online version it usually means the user hasn't cleared his cache since the last new version.

**Comment by Rydion** [comment]
@bromagosa Yeah I had seen that some automated solutions exist but I didn't want to drift to far away from the original implementation to avoid as many issues as possible. But if the mac versions keeps fucking around I may look into it sooner than later.

As for the problem at hand, I have replaced the entire Mac OS Nw.js folder with the one that was being used before and double checked that everything that has to be executable has the correct flags set. If someone could try one last time to see if it works I would be very thankful.

This is all I can do at the moment without a Mac on which I can develop on. If  it fails again I'll try to borrow one, but it could take a little while.

**Comment by micahcowan** [comment]
So, I just tried it for OS X 64-bit, and got @brianharvey's console error messages (and big white window) for what he said he got after marking "njws Helper" executable. (The stuff starting with `TypeError: Cannot read property 'hasOwnProperty' of undefined` and the like: JavaScript errors).

**Comment by micahcowan** [comment]
So, a comment. According to those error messages, the offending code lies within the `enableRetinaSupport()` function in morphic.js, at this spot:

```javascript
    if (Object.keys(uber).some(function (any) {
        var prop = uber[any];
        return prop.hasOwnProperty('configurable') && (!prop.configurable);
    })) {return; }
```

(and `uber` is a local variable defined just above, whose value is a `{}`-style object with explicitly-defined keys).

It would seem, from those error messages, that the anonymous function passed as argument to `.some()` is somehow getting passed a name that doesn't correspond to a property, or at any rate `prop` gets set to `undefined` from a lookup that's meant to be performed on a list we generated of keys we know exist(?!). No idea how that's happening...

But it seems that part of the problem may be that we're exercising a portion of the Snap! JavaScript code that obviously only gets exercised on Macs. Disabling the retina support (or the possibility of enableRetinaSupport()) might at least get you a runnable app, and then you can deal with restoring the support... it would seem that the "app layout" parts of the Mac OS X generation is at least working now.

**Comment by Rydion** [comment]
Hi thank you for the feedback. Yeah it seems to be something related only to Mac OS as the Windows and Linux versions work just fine.

The version of NW.js I'm using is quite old, maybe that's the problem.

**Comment by micahcowan** [comment]
I did a little further digging.

prop gets set to undef for all five of the properties that are copied from `HTMLCanvasElement.prototype`: `height`, `width`, `shadowOffsetX`, etc...

I modified the line

```javascript
return prop.hasOwnProperty('configurable') && (!prop.configurable);
```

in the offending snippet I copy/pasted, and made it:

```javascript
return prop === undefined || (prop.hasOwnProperty('configurable') && (!prop.configurable));
```

which causes an early exit from `enableRetinaSupport()`, with the net result that retina support is disabled. _But_, it allows the app to proceed, and it appears to work normally. Except that it is of course very blurry on my retina display. ^_^

Anyway, the conclusion would seem to be that either the retina support code in Snap! just doesn't work with NW.js (perhaps because those properties don't derive from `HTMLCanvasElement`'s prototype, but are added in at construction, or perhaps you're right that a newer NW.js will "just fix" this issue (while inevitably introducing new incompatibilities with your current setup, I'm sure ;) )

**Comment by micahcowan** [comment]
(For anyone following along, wondering where exactly the code lives that I was modifying, I found that `Contents/Resources/app.nw` within the app is just a zip file containing the Snap! source code, where `gui.js` is modified to adapt it to  NW.js, and to include the contents of the uploaded `.xml` project file inline as a string value. So I just unpacked the zip and repacked it to test these code changes.)

**Comment by Rydion** [comment]
@micahcowan  Awesome! Thank you.
I'll apply this fix to the Snap! code used by Snapp! until I find a way to make it work (I'm pretty sure a newer version should be compatible with this retina stuff).

PS: Is the image quality good enough to be usable?

**Comment by brianharvey** [comment]
Yes, it's usable without retina support, but you can definitely tell, mainly with respect to fonts, e.g., the names of the blocks.

And yes, I'm sure an up-to-date node.js will fix this.

**Comment by micahcowan** [comment]
Here's an example on the default 1024x768-sized app window (click to view it at 1:1):
![image](https://cloud.githubusercontent.com/assets/4712979/21913099/082378ca-d8df-11e6-8486-61a2b33b5631.png)

And here's one at 600x450:
![image](https://cloud.githubusercontent.com/assets/4712979/21913132/32854c38-d8df-11e6-8f6d-f56c853740bb.png)

(project is http://snap.berkeley.edu/snapsource/snap.html#present:Username=micahcowan&ProjectName=list-render)

So, it depends somewhat on the app window size, and your definition of "usable" maybe 😄

**Comment by Rydion** [comment]
Well it could be worse I guess... Still I'll try to get it sorted out as soon as I can get my hands on a Mac to properly test this stuff so that I don't need to bother you every 5 minutes. 😄

I've pushed the workaround, the Mac OS executables should be working correctly (I hope).

**Comment by brianharvey** [comment]
Confirming, I can now run apps!  Thanks!

**Comment by nathalierun** [comment]
Le 13/01/2017 à 04:11, Adrian Hintze a écrit :
> I've pushed the workaround, the Mac OS executables should be working
> correctly (I hope).

Hello,

Thank you for this work !!! (I was really waiting for it...)

I just tested on one of my projects. It works with Firefox, but Chrome
turn and turn and never finish.

Another thing is that when I open http://snapp.citilab.eu/ , it proposes
me a OS X 32 bits target OS but I work now on a 64 bits (OS X El Capitan
on a MacBook Retina 12-inch early 2016).

**Comment by Rydion** [comment]
@nathalierun

I've tested the application with Chrome, Firefox, IE 11 and Edge and it
should work on all of them. It fails on Safari (next on my list).

The machine on which Snapp! is currently running is rather underwhelming
and I've had it take quite a while to finish but it should, eventually.
There's a pending improvement that will speed it up a little bit, but still
don't expect a great difference.

The thing with detecting the right OS version is a little bit tricky. It
only works 100% correctly on Windows. Anyways I was thinking about
scrapping the 32 bit Mac version completely. As far as I know all modern
Macs should be 64 bit.

I hope all projects will be working smoothly from now on. If you find any
other Snapp! related problems just let me know over at
https://github.com/Rydion/Snapp/.
