### ISSUE TITLE
Relabelling if-else to if triggers exception 

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap--Build-Your-Own-Blocks#1630]
It works fine but in the console one sees:

Uncaught TypeError: Cannot read property 'moveBy' of null
    at http://snap.berkeley.edu/snapsource/blocks.js:2785:16
    at Array.forEach (native)
    at CommandBlockMorph.BlockMorph.setSelector (http://snap.berkeley.edu/snapsource/blocks.js:2784:17)
    at CommandBlockMorph.<anonymous> (http://snap.berkeley.edu/snapsource/blocks.js:2759:24)
    at MenuItemMorph.TriggerMorph.trigger (http://snap.berkeley.edu/snapsource/morphic.js:9267:25)
    at MenuItemMorph.mouseClickLeft (http://snap.berkeley.edu/snapsource/morphic.js:9562:14)
    at HandMorph.processMouseUp (http://snap.berkeley.edu/snapsource/morphic.js:10781:29)
    at HTMLCanvasElement.<anonymous> (http://snap.berkeley.edu/snapsource/morphic.js:11439:25)

**Comment by jmoenig** [comment]
Good catch, thank!
I'll fix it...
